# Run these on the local machine

start-bench NAMESPACE:
    kubectl create secret generic hf-token-secret --from-literal=HF_TOKEN="$HF_TOKEN" -n {{NAMESPACE}}
    kubectl apply -n {{NAMESPACE}} -f manifest.yaml

delete-bench NAMESPACE:
    kubectl delete pod -n {{NAMESPACE}} benchmark-interactive

exec-bench NAMESPACE:
    kubectl cp Justfile.remote {{NAMESPACE}}/benchmark-interactive:/app/Justfile && \
    kubectl cp sweep.sh {{NAMESPACE}}/benchmark-interactive:/app/sweep.sh && \
    kubectl exec -it -n {{NAMESPACE}} benchmark-interactive -- /bin/bash

copy-results NAMESPACE FILENAME:
    kubectl cp {{NAMESPACE}}/benchmark-interactive:/app/{{FILENAME}} ./{{FILENAME}}
