repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-kv-events
    namespace: llm-d
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: 1.0.5
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: ms-kv-events
    namespace: llm-d
    chart: llm-d-modelservice/llm-d-modelservice
    version: 0.0.18
    installed: true
    needs:
      - llm-d/infra-kv-events
    values:
      - ms-kv-events/values.yaml
    labels:
      managedBy: helmfile
    hooks:
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            echo "Patching HTTPRoute to trigger reconciliation..."
            kubectl patch httproute ms-kv-events-llm-d-modelservice \
              -n llm-d \
              -p '{"metadata":{"labels":{"inferencepool":"ms-kv-events-llm-d-modelservice"}}}' \
              --type=merge
