# Run these on the local machine

POD_NAME := "interactive-pod"

start-bench NAMESPACE:
    kubectl apply -n {{NAMESPACE}} -f manifest.yaml

delete-bench NAMESPACE:
    kubectl delete pod -n {{NAMESPACE}} {{POD_NAME}}

exec-bench NAMESPACE:
    kubectl cp Justfile.remote {{NAMESPACE}}/{{POD_NAME}}:/app/Justfile && \
    kubectl cp sweep.sh {{NAMESPACE}}/{{POD_NAME}}:/app/sweep.sh && \
    kubectl exec -it -n {{NAMESPACE}} {{POD_NAME}} -- /bin/bash

copy-results NAMESPACE FILENAME:
    kubectl cp {{NAMESPACE}}/{{POD_NAME}}:/app/{{FILENAME}} ./{{FILENAME}}
